### ISSUE TITLE
Support Objectos HTML move to the way package

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.selfgen#1]
## Tasks

- [x] html: generate HtmlAttributeNameBase (was GeneratedAttributeName)
- [x] html: generate HtmlCompilerAttributes
- [x] html: generate Html.TemplateElements
- [x] html: generate Html.CompilerElements
- [x] html: generate HtmlElementNameBase (was StandardElementName)
- [x] html: generate HtmlCompilerElements
- [x] html: the clip-path element/attribute
- [x] html: elements with no end tag must reject only element instructions
